const { Pool, Client } = require('pg')
const db = new Pool({user: 'postgres',
			 host: 'localhost',
			 database: 'onrr_db',
			 password: 'secret',
			 port: 5433,
			});



let period_lookup={};
let commodity_lookup={};
let location_lookup={};

const main = () => {
//    db.query('select * from foo', (err, res) => {
//	console.log(err, res)
	//db.end()
    //    });
     commodity_table();
     location_table();
    period_table();
    revenue_table();
   revenue_trends();
    
}

const revenue_table = () => {
    let table=`
CREATE TABLE  IF NOT EXISTS
revenue( 
  location_id integer references location, 
  period_id integer references period, 
  commodity_id integer references commodity, 
  revenue real,
  raw_revenue varchar(255),
  primary key (location_id, period_id, commodity_id)
  
)
`
    db.query(table);
    
}

const period_table = () => {
    let table=`
CREATE TABLE  IF NOT EXISTS
period(
  period_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  period varchar(255),
  calendar_year integer,
  fiscal_year integer, 
  month integer, 
  month_long varchar(255),
  fiscal_month integer, 
  period_date date,
  UNIQUE(period,calendar_year,fiscal_year,month, month_long,fiscal_month, period_date)
)

`    
    //const create=db.prepare(table)
    db.query(table);
}


const commodity_table = () => {
    let table=`
CREATE TABLE  IF NOT EXISTS
commodity(
  commodity_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
  product varchar(255), 
  commodity varchar(255),  
  revenue_type varchar(255),
  revenue_category varchar(255), 
  mineral_lease_type varchar(255), 
  UNIQUE(product,commodity,revenue_type,revenue_category, mineral_lease_type)
)
`

    db.query(table);

}



const location_table = () => {


    let table=`
CREATE TABLE IF NOT EXISTS
location (
   location_id  int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
   fips_code  varchar(5), 
   state varchar(255),  
   county varchar(255),  
   land_class varchar(255),
   land_category varchar(255) , 
   offshore_region varchar(255), 
   offshore_planning_area varchar(255),
   offshore_planning_area_code varchar(3), 
   offshore_block varchar(255), 
   offshore_protraction varchar (255), 
   UNIQUE(fips_code,state,county,land_class,land_category,offshore_region,offshore_planning_area,offshore_planning_area_code,offshore_block,offshore_protraction)
)
`
    db.query(table)
    
}

const revenue_trends = () => {
    let view=`
CREATE view revenue_trends as
select fiscal_year, 
       case when (revenue_type='Other Revenues' or revenue_type='Civil Penalties' or revenue_type='Inspection Fees') then 'Other Revenues' else  revenue_type end as trend_type,  
       (select month_long from period where period_date=(select max(period_date) from period where period_date <= '2019-07-01')) as current_month,
       sum(case when fiscal_month <= (select fiscal_month from period where period_date=(select max(period_date) from period where period_date <= '2019-07-01' )) then revenue else 0 end) as total_ytd, 
       sum(revenue) as total 
from revenue 
  natural join period 
  natural join commodity 
where commodity is not null
and period_date <= '2019-07-01'
group by fiscal_year, trend_type

union 
select fiscal_year,  
       'All Revenue' as trend_type,
       (select month_long from period where period_date=(select max(period_date) from period where period_date <= '2019-07-01' )) as current_month,
       sum(case when fiscal_month <= (select fiscal_month from period where period_date=(select max(period_date) from period where period_date <= '2019-07-01')) then revenue else 0 end) as total_ytd, 
       sum(revenue) as total 
from revenue natural join period natural join commodity 
where commodity is not null and  period_date <= '2019-07-01'
group by fiscal_year;

`
    db.query(view);

}


main();
